# Config file for automatic testing at travis-ci.org

language: python
python: 3.5
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pep8

install: pip install -U tox
script: tox
before_install:
  - pip install codecov
after_success:
  - codecov
